{% set prefix = DEFAULT_CONTAINER_REGISTRY %}
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y apt-transport-https \
                                         apt-utils \
                                         build-essential \
                                         ca-certificates \
                                         cmake \
                                         conserver-client \
                                         curl \
                                         default-jre \
                                         git \
                                         gnupg \
                                         gnupg-agent \
                                         iproute2 \
                                         iputils-ping \
                                         isc-dhcp-client \
                                         libffi-dev \
                                         libnanomsg-dev \
                                         libssl-dev \
                                         libxml2 \
                                         libxslt1-dev \
                                         lsb-release \
                                         jq \
                                         openssh-server \
                                         protobuf-compiler \
                                         psmisc \
                                         python3-pip \
                                         python3-venv \
                                         python3-protobuf \
                                         rsyslog \
                                         shellcheck \
                                         snmp \
                                         software-properties-common \
                                         sshpass \
                                         sudo \
                                         tcpdump \
                                         telnet \
                                         vim

RUN python3 -m pip install --break-system-packages aiohttp \
                 allure-pytest==2.8.22 \
                 ansible==9.12.0 \
                 azure-storage-blob==12.9.0 \
                 azure-kusto-data \
                 azure-kusto-ingest \
                 defusedxml \
                 celery[redis]==5.2.7 \
                 cffi \
                 contextlib2==0.6.0.post1 \
                 ctypesgen \
                 dpkt \
                 dpugen==0.1.1 \
                 "future>=0.16.0" \
                 gitpython \
                 ipaddr \
                 ipython==8.12.2 \
                 ixload \
                 ixnetwork-restpy==1.0.64 \
                 ixnetwork-open-traffic-generator==0.0.79 \
                 jinja2==3.1.2 \
                 jsonpatch \
                 lxml \
                 markupsafe==2.0.1 \
                 mock \
                 msrest==0.6.21 \
                 natsort \
                 ncclient \
                 netaddr \
                 netmiko==4.4.0 \
                 pandas \
                 paramiko==3.5.0 \
                 passlib \
                 pexpect \
                 prettytable \
                 psutil \
                 ptf \
                 pyasn1==0.4.8 \
                 pycryptodome==3.9.8 \
                 pyfiglet \
                 pylint==1.8.1 \
                 pyro4 \
                 pysnmp==7.1.6 \
                 pysubnettree \
                 pytest-ansible==4.0.0 \
                 pytest-html \
                 pytest-repeat \
                 pytest-xdist==1.28.0 \
                 python-dateutil \
                 pytest==7.4.0 \
                 PyYAML \
                 redis \
                 requests \
                 retry \
                 rpyc \
                 scandir \
                 scapy==2.5.0 \
                 setuptools-rust \
                 six \
                 snappi==1.17.1 \
                 snappi-ixnetwork==1.17.0 \
                 tabulate \
                 textfsm==1.1.3 \
                 thrift==0.11.0 \
                 virtualenv \
                 nnpy

# Install docker-ce-cli
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -                                        \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"    \
    && apt-get update                                                                                              \
    && apt-get install -y docker-ce-cli

# Install Azure CLI, following https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions
RUN mkdir -p /etc/apt/keyrings \
    && curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null \
    && chmod go+r /etc/apt/keyrings/microsoft.gpg \
    && echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ `lsb_release -cs` main" | tee /etc/apt/sources.list.d/azure-cli.list \
    && apt-get update && apt-get install -y azure-cli

## Copy and install sonic-mgmt docker dependencies
COPY debs/sonic-device-data_*.deb debs/libdashapi_*.deb debs/

RUN dpkg -i debs/sonic-device-data_*.deb debs/libdashapi_*.deb

RUN mkdir /var/run/sshd
EXPOSE 22

# Add user
ARG user
ARG uid
ARG guid
ARG hostname

ENV BUILD_HOSTNAME $hostname
ENV USER $user
ENV CC=gcc CPP=cpp CXX=c++ LDSHARED="gcc -pthread -shared" PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1

RUN deluser --remove-home ubuntu
RUN addgroup --gid $guid g$user
RUN adduser $user --uid $uid --gid $guid --home /var/$user --shell /bin/bash

COPY sonic-jenkins.pub /var/$user/.ssh/authorized_keys2

RUN echo "Host *\n\tStrictHostKeyChecking no\n" > /var/$user/.ssh/config
RUN chown $user /var/$user/.ssh -R
RUN chmod go= /var/$user/.ssh -R

# Add user to sudoers
RUN echo "$user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER $user
WORKDIR /var/$user

# Add az symlink for backwards compatibility
RUN mkdir bin && ln -s /usr/bin/az bin/az

USER root
WORKDIR /azp
COPY start.sh \
     0001-Fix-getattr-AttributeError-in-multi-thread-scenario.patch \
     ./
RUN chmod +x start.sh \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf `which pip3` /usr/bin/pip \
    && patch -u -b /usr/local/lib/python3.12/dist-packages/ansible/plugins/loader.py -i /azp/0001-Fix-getattr-AttributeError-in-multi-thread-scenario.patch

USER $user
WORKDIR /var/$user
